services:
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: "crowdsec"
    hostname: "crowdsec"
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    environment:
      COLLECTIONS: "crowdsecurity/http-cve crowdsecurity/http-dos crowdsecurity/base-http-scenarios crowdsecurity/traefik"
      CUSTOM_HOSTNAME: crowdsec
      BOUNCER_KEY_PLUGIN: password
    volumes:
      - ../config/acquis.yml:/etc/crowdsec/acquis.yaml:ro
      - ${DATA_PATH}/crowdsec:/var/lib/crowdsec/data/
      - ${LOG_PATH}/traefik:/var/log/traefik:ro
    networks:
      crowdsec-internal:
        ipv4_address: 172.20.255.254
