services:
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: "crowdsec"
    hostname: "crowdsec"
    restart: unless-stopped
    environment:
      COLLECTIONS: "crowdsecurity/http-cve crowdsecurity/http-dos crowdsecurity/base-http-scenarios crowdsecurity/traefik"
      CUSTOM_HOSTNAME: crowdsec
      BOUNCER_KEY_PLUGIN: password
    volumes:
      - ${VOLUME_PATH}/crowdsec:/var/lib/crowdsec/data/
      - ../config/acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - /var/log/traefik:/var/log/traefik:ro
    networks:
      crowdsec-internal:
        ipv4_address: 172.20.255.254
