services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.${DOMAIN}`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=cloudflare"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.services.nextcloud.loadbalancer.passHostHeader=true"
      - "traefik.docker.network=reverse-proxy"
    secrets:
      - NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_REDIS_HOST_PASSWORD
      - NEXTCLOUD_POSTGRES_PASSWORD
    env_file:
      - ../config/nextcloud.env
    volumes:
      - ../.docker/data/nextcloud:/var/www/html:rw
      - ../.docker/logs/nextcloud:/var/log/nextcloud:rw
      - ../scripts/nextcloud-post-installation.sh:/docker-entrypoint-hooks.d/post-installation/nextcloud-post-installation.sh:ro
    networks:
      - reverse-proxy
      - nextcloud-internal
    depends_on:
      nextcloud-database:
        condition: service_healthy
      nextcloud-redis:
        condition: service_started
  nextcloud-database:
    image: postgres:latest
    container_name: nextcloud-database
    hostname: nextcloud-database
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextcloud -d nextcloud"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - NEXTCLOUD_POSTGRES_PASSWORD
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD_FILE=/run/secrets/NEXTCLOUD_POSTGRES_PASSWORD
      - POSTGRES_DB=nextcloud
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ../.docker/data/nextcloud-database:/var/lib/postgresql/data:rw
    networks:
      - nextcloud-internal
  nextcloud-redis:
    image: redis:latest
    container_name: nextcloud-redis
    hostname: redis
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    secrets:
      - NEXTCLOUD_REDIS_HOST_PASSWORD
    volumes:
      - ../.docker/data/nextcloud-redis:/data
    networks:
      - nextcloud-internal
    command: bash -c 'redis-server --requirepass "$$(cat /run/secrets/NEXTCLOUD_REDIS_HOST_PASSWORD)"'
  nextcloud-cron:
    image: nextcloud:latest
    container_name: nextcloud-cron
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    secrets:
      - NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_REDIS_HOST_PASSWORD
      - NEXTCLOUD_POSTGRES_PASSWORD
    env_file:
      - ../config/nextcloud.env
    volumes:
      - ../.docker/data/nextcloud:/var/www/html:rw
    entrypoint: /cron.sh
    networks:
      - nextcloud-internal
    depends_on:
      nextcloud:
        condition: service_started
secrets:
  NEXTCLOUD_ADMIN_PASSWORD:
    file: ../.docker/secrets/NEXTCLOUD_ADMIN_PASSWORD
  NEXTCLOUD_POSTGRES_PASSWORD:
    file: ../.docker/secrets/NEXTCLOUD_POSTGRES_PASSWORD
  NEXTCLOUD_REDIS_HOST_PASSWORD:
    file: ../.docker/secrets/NEXTCLOUD_REDIS_HOST_PASSWORD
