services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    hostname: nextcloud
    restart: unless-stopped
    user: "2022:2022"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.nextcloud-secure.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`cloud.${DOMAIN}`)"
      - "traefik.http.routers.nextcloud-secure.middlewares=nc-rep,nc-header"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.middlewares.nc-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-rep.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nc-rep.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc-header.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nc-header.headers.customResponseHeaders.Strict-Transport-Security=15552000"
    secrets:
      - NEXTCLOUD_REDIS_HOST_PASSWORD
      - NEXTCLOUD_MYSQL_PASSWORD
    environment:
      - TRUSTED_PROXIES=172.30.255.254/16
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.${DOMAIN}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=test
      #- REDIS_HOST_PASSWORD_FILE=/run/secrets/NEXTCLOUD_REDIS_HOST_PASSWORD
      - MYSQL_HOST=mariadb
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=test
      #- MYSQL_PASSWORD_FILE=/run/secrets/NEXTCLOUD_MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
    volumes:
      - /mnt/data/nextcloud:/var/www/html:rw
      # https://github.com/nextcloud/docker/issues/1494
      - /mnt/data/.fix/remoteip.conf:/etc/apache2/conf-enabled/remoteip.conf:ro
      # https://github.com/nextcloud/docker/issues/763
      - /mnt/data/.fix/redis-session.ini:/usr/local/etc/php/conf.d/redis-session.ini:rw
    networks:
      reverse-proxy:
        ipv4_address: 172.30.255.253
      nextcloud-net:
        ipv4_address: 172.32.255.254
    depends_on:
      - mariadb
      - redis
  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    user: "2022:2022"
    secrets:
      - NEXTCLOUD_MYSQL_ROOT_PASSWORD
      - NEXTCLOUD_MYSQL_PASSWORD
    environment:
      - MYSQL_ROOT_PASSWORD=test
      #- MYSQL_ROOT_PASSWORD_FILE=/run/secrets/NEXTCLOUD_MYSQL_ROOT_PASSWORD
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=test
      #- MYSQL_PASSWORD_FILE=/run/secrets/NEXTCLOUD_MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - /mnt/data/mysql:/var/lib/mysql:rw
    networks:
      nextcloud-net:
        ipv4_address: 172.32.255.253
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --skip-innodb-read-only-compressed
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: unless-stopped
    user: "2022:2022"
    secrets:
      - NEXTCLOUD_REDIS_HOST_PASSWORD
    networks:
      nextcloud-net:
        ipv4_address: 172.32.255.252
    command: redis-server --requirepass test
networks:
  nextcloud-net:
    name: "nextcloud-net"
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16
    attachable: true
    internal: true
