services:
  nextcloud:
    image: nextcloud:latest
    container_name: "nextcloud"
    hostname: "nextcloud"
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.${DOMAIN}`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=cloudflare"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.routers.nextcloud.middlewares=nc-header"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.services.nextcloud.loadbalancer.passHostHeader=true"
      - "traefik.http.middlewares.nc-header.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nc-header.headers.customResponseHeaders.Strict-Transport-Security=15552000"
      - "traefik.docker.network=reverse-proxy"
    secrets:
      - NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_REDIS_HOST_PASSWORD
      - NEXTCLOUD_POSTGRES_PASSWORD
    environment:
      - TRUSTED_PROXIES=172.18.255.254/16
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.${DOMAIN}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/NEXTCLOUD_ADMIN_PASSWORD
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD_FILE=/run/secrets/NEXTCLOUD_REDIS_HOST_PASSWORD
      - POSTGRES_HOST=nextcloud-database
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD_FILE=/run/secrets/NEXTCLOUD_POSTGRES_PASSWORD
      - POSTGRES_DB=nextcloud
    volumes:
      - ${DATA_PATH}/nextcloud:/var/www/html:rw
    networks:
      - reverse-proxy
      - nextcloud-internal
    depends_on:
      nextcloud-database:
        condition: service_healthy
      nextcloud-redis:
        condition: service_started
  nextcloud-database:
    image: postgres:latest
    container_name: "nextcloud-database"
    hostname: "nextcloud-database"
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nextcloud"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - NEXTCLOUD_POSTGRES_PASSWORD
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD_FILE=/run/secrets/NEXTCLOUD_POSTGRES_PASSWORD
      - POSTGRES_DB=nextcloud
      - PGUSER=postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${DATA_PATH}/nextcloud-database:/var/lib/postgresql/data:rw
    networks:
      - nextcloud-internal
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --skip-innodb-read-only-compressed
  nextcloud-redis:
    image: redis:latest
    container_name: "nextcloud-redis"
    hostname: "redis"
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    secrets:
      - NEXTCLOUD_REDIS_HOST_PASSWORD
    volumes:
      - ${DATA_PATH}/nextcloud-redis:/data
    networks:
      - nextcloud-internal
    command: bash -c 'redis-server --requirepass "$$(cat /run/secrets/NEXTCLOUD_REDIS_HOST_PASSWORD)"'
secrets:
  NEXTCLOUD_ADMIN_PASSWORD:
    file: ${DATA_PATH}/secrets/NEXTCLOUD_ADMIN_PASSWORD
  NEXTCLOUD_POSTGRES_PASSWORD:
    file: ${DATA_PATH}/secrets/NEXTCLOUD_POSTGRES_PASSWORD
  NEXTCLOUD_REDIS_HOST_PASSWORD:
    file: ${DATA_PATH}/secrets/NEXTCLOUD_REDIS_HOST_PASSWORD
