services:
  nextcloud:
    image: nextcloud:latest
    container_name: "nextcloud"
    hostname: "nextcloud"
    restart: unless-stopped
    user: "2022:2022"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.${DOMAIN}`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=cloudflare"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.routers.nextcloud.middlewares=nc-header"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.services.nextcloud.loadbalancer.passHostHeader=true"
      - "traefik.http.middlewares.nc-header.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nc-header.headers.customResponseHeaders.Strict-Transport-Security=15552000"
      - "traefik.docker.network=reverse-proxy"
    secrets:
      - NEXTCLOUD_REDIS_HOST_PASSWORD
      - NEXTCLOUD_MYSQL_PASSWORD
    environment:
      - TRUSTED_PROXIES=172.30.255.254/16
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.${DOMAIN}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD_FILE=/run/secrets/NEXTCLOUD_REDIS_HOST_PASSWORD
      - MYSQL_HOST=mysql
      - MYSQL_USER=nextcloud
      #- MYSQL_PASSWORD_FILE=/run/secrets/NEXTCLOUD_MYSQL_PASSWORD
      - MYSQL_PASSWORD="test"
      - MYSQL_DATABASE=nextcloud
    volumes:
      - /mnt/data/nextcloud:/var/www/html:rw
      # https://github.com/nextcloud/docker/issues/1494
      - /mnt/data/.fix/remoteip.conf:/etc/apache2/conf-enabled/remoteip.conf:ro
      # https://github.com/nextcloud/docker/issues/763
      - /mnt/data/.fix/redis-session.ini:/usr/local/etc/php/conf.d/redis-session.ini:rw
    networks:
      - reverse-proxy
      - nextcloud-net
    depends_on:
      - nextcloud-mysql
      - nextcloud-redis
  nextcloud-mysql:
    image: mariadb:11.4
    container_name: "nextcloud-mysql"
    hostname: "mysql"
    restart: unless-stopped
    user: "2022:2022"
    secrets:
      - NEXTCLOUD_MYSQL_ROOT_PASSWORD
      - NEXTCLOUD_MYSQL_PASSWORD
    environment:
      #- MYSQL_ROOT_PASSWORD_FILE=/run/secrets/NEXTCLOUD_MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_PASSWORD="test"
      - MYSQL_USER=nextcloud
      #- MYSQL_PASSWORD_FILE=/run/secrets/NEXTCLOUD_MYSQL_PASSWORD
      - MYSQL_PASSWORD="test"
      - MYSQL_DATABASE=nextcloud
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - /mnt/data/nextcloud-mysql:/var/lib/mysql:rw
    networks:
      - nextcloud-net
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --skip-innodb-read-only-compressed
  nextcloud-redis:
    image: redis:latest
    container_name: "nextcloud-redis"
    hostname: "redis"
    restart: unless-stopped
    user: "2022:2022"
    secrets:
      - NEXTCLOUD_REDIS_HOST_PASSWORD
    networks:
      - nextcloud-net
    command: bash -c 'redis-server --requirepass "$$(cat /run/secrets/NEXTCLOUD_REDIS_HOST_PASSWORD)"'
networks:
  nextcloud-net:
    name: "nextcloud-net"
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16
    attachable: true
    internal: true
secrets:
  NEXTCLOUD_MYSQL_ROOT_PASSWORD:
    file: /mnt/data/secrets/NEXTCLOUD_MYSQL_ROOT_PASSWORD
  NEXTCLOUD_MYSQL_PASSWORD:
    file: /mnt/data/secrets/NEXTCLOUD_MYSQL_PASSWORD
  NEXTCLOUD_REDIS_HOST_PASSWORD:
    file: /mnt/data/secrets/NEXTCLOUD_REDIS_HOST_PASSWORD
