services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.tls=true
      - traefik.http.routers.nginx.tls.certresolver=cloudflare
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.rule=Host(`test.${DOMAIN}`)
    networks:
      - reverse-proxy
