- filenames:
    - /var/log/traefik/access.log
  poll_without_inotify: true
  labels:
    type: traefik

- filenames:
    - /var/log/nextcloud/nextcloud.log
  labels:
    type: Nextcloud

- filenames:
    - /var/log/vaultwarden/vaultwarden.log
  labels:
    type: vaultwarden

- filenames:
    - /var/log/auth.log
    - /var/log/syslog
  labels:
    type: syslog
