---
filenames:
  - /var/log/traefik/access.log
  - /var/log/traefik/traefik.log
poll_without_inotify: true
labels:
  type: traefik
---
filenames:
 - /var/log/nextcloud.log
labels:
  type: nextcloud
---
filenames:
 - /var/log/vaultwarden/vaultwarden.log
labels:
  type: vaultwarden
---
filenames:
  - /var/log/auth.log
  - /var/log/syslog
labels:
  type: syslog

