http:
  middlewares:
    crowdsec-bouncer:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          CrowdsecLapiKey: "password"
          Enabled: true
    security-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        frameDeny: true
        referrerPolicy: "no-referrer"
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        customResponseHeaders:
          X-Content-Type-Options: "nosniff"
          X-Frame-Options: "SAMEORIGIN"
          X-XSS-Protection: "1; mode=block"
          Referrer-Policy: "no-referrer"
          Strict-Transport-Security: "max-age=63072000; includeSubDomains; preload"
          Permissions-Policy: "geolocation=(), microphone=()"
          X-Robots-Tag: "noindex, nofollow"
