name: Lint Docker Compose Files

on:
  pull_request:
    paths:
      - 'docker-compose.yml'
      - 'crowdsec/compose.yml'
      - 'nextcloud/compose.yml'
      - 'traefik/compose.yml'
      - 'vaultwarden/compose.yml'
  push:
    paths:
      - 'docker-compose.yml'
      - 'crowdsec/compose.yml'
      - 'nextcloud/compose.yml'
      - 'traefik/compose.yml'
      - 'vaultwarden/compose.yml'

jobs:
  lint-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Lint Docker Compose files
        uses: docker-compose-linter/dclint-github-action@v1.4.0
        with:
          path: |
            ./docker-compose.yml
            ./crowdsec/compose.yml
            ./nextcloud/compose.yml
            ./traefik/compose.yml
            ./vaultwarden/compose.yml
          recursive: false
