services:
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: "crowdsec"
    hostname: "crowdsec"
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    environment:
      COLLECTIONS: "crowdsecurity/http-cve crowdsecurity/http-dos crowdsecurity/base-http-scenarios crowdsecurity/traefik crowdsecurity/nextcloud Dominic-Wagner/vaultwarden"
      CUSTOM_HOSTNAME: crowdsec
      BOUNCER_KEY_traefik: password
    volumes:
      - ./acquis.yml:/etc/crowdsec/acquis.yaml:ro
      - crowdsec:/var/lib/crowdsec/data/:rw
      - nextcloud-logs:/var/log/nextcloud:ro
      - traefik-logs:/var/log/traefik:ro
      - vaultwarden-logs:/var/log/vaultwarden:ro
    networks:
      crowdsec-internal:
        ipv4_address: 172.29.255.254
